Traceback (most recent call last):
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/long/miniforge3/envs/codebook_env/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/long/Library/CloudStorage/OneDrive-Personal/Projects/Crop_Variaties/.venv/ag_policies_codebook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import libraries
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
import time
from time import sleep
import pandas as pd
import datefinder
import calendar
import os
import unittest
from random import randint
import PyPDF2
import glob
import pickle
import numpy as np
import fitz
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# import libraries[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m [38;5;28;01mimport[39;00m webdriver
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwebdriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcommon[39;00m[38;5;21;01m.[39;00m[38;5;21;01mby[39;00m [38;5;28;01mimport[39;00m By
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mselenium[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwebdriver[39;00m[38;5;21;01m.[39;00m[38;5;21;01msupport[39;00m[38;5;21;01m.[39;00m[38;5;21;01mui[39;00m [38;5;28;01mimport[39;00m WebDriverWait

[0;31mModuleNotFoundError[0m: No module named 'selenium'

